-- =========================================================================
-- SQL Migration Script: Socioeconomic and Household Context Module (Hogar)
-- =========================================================================

-- 1. Create public.hogar table
CREATE TABLE IF NOT EXISTS public.hogar (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  barrio text,
  localidad text,
  tipo_barrio text CHECK (tipo_barrio IN ('formal', 'informal')),
  id_adulto_jefe bigint REFERENCES public.adultos(id) ON DELETE SET NULL,
  tipo_hogar text CHECK (tipo_hogar IN ('unipersonal', 'nuclear', 'extendido', 'compuesto', 'monoparental_maternal', 'monoparental_paternal')),
  jefatura text CHECK (jefatura IN ('femenina', 'masculina', 'compartida')),
  cant_personas integer DEFAULT 1,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for public.hogar
ALTER TABLE public.hogar ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow authenticated select on hogar" 
  ON public.hogar FOR SELECT 
  TO authenticated 
  USING (true);

CREATE POLICY "Allow authenticated insert on hogar" 
  ON public.hogar FOR INSERT 
  TO authenticated 
  WITH CHECK (true);

CREATE POLICY "Allow authenticated update on hogar" 
  ON public.hogar FOR UPDATE 
  TO authenticated 
  USING (true);

-- 2. Create public.hogar_snapshot table
CREATE TABLE IF NOT EXISTS public.hogar_snapshot (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_hogar bigint REFERENCES public.hogar(id) ON DELETE CASCADE NOT NULL,
  fecha timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  
  -- Education & Employment
  nivel_educativo_jefe text CHECK (nivel_educativo_jefe IN ('primario_incompleto', 'primario_completo', 'secundario_incompleto', 'secundario_completo', 'terciario_universitario_incompleto', 'terciario_universitario_completo')),
  situacion_ocupacional text CHECK (situacion_ocupacional IN ('formal', 'informal', 'desocupado', 'inactivo')),
  escala_ingresos text CHECK (escala_ingresos IN ('menos_1_sml', 'entre_1_2_sml', 'entre_2_3_sml', 'mas_3_sml')),
  recibe_transferencias_estado boolean DEFAULT false,
  tipo_transferencias text[] DEFAULT '{}',
  
  -- Housing & Health
  cobertura_salud text CHECK (cobertura_salud IN ('publica', 'obra_social', 'prepaga')),
  tipo_vivienda text CHECK (tipo_vivienda IN ('casa', 'departamento', 'pieza_inquilinato', 'rancho_casilla', 'otra')),
  condicion_tenencia text CHECK (condicion_tenencia IN ('propietario', 'inquilino', 'ocupante_de_hecho', 'prestada_otra')),
  material_piso text CHECK (material_piso IN ('tierra', 'cemento_ladrillo', 'ceramico_mosaico', 'madera_otro')),
  cant_ambientes integer DEFAULT 1,
  hacinamiento text CHECK (hacinamiento IN ('sin_hacinamiento', 'hacinamiento', 'hacinamiento_critico')),
  
  -- Services & Infrastructure
  agua text CHECK (agua IN ('red_publica', 'pozo', 'otra')),
  saneamiento text CHECK (saneamiento IN ('red_cloacal', 'pozo', 'sin_sistema')),
  electricidad text CHECK (electricidad IN ('con_medidor', 'irregular', 'sin_acceso')),
  combustible_coccion text CHECK (combustible_coccion IN ('gas_red', 'garrafa', 'lena', 'electricidad')),
  tiene_internet boolean DEFAULT false,
  
  -- Networks & Support
  tiene_red_apoyo boolean DEFAULT false,
  tipo_red_apoyo text[] DEFAULT '{}',
  participa_organizacion boolean DEFAULT false,
  tipo_organizacion text[] DEFAULT '{}',
  observaciones text,
  
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for public.hogar_snapshot
ALTER TABLE public.hogar_snapshot ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow authenticated select on hogar_snapshot" 
  ON public.hogar_snapshot FOR SELECT 
  TO authenticated 
  USING (true);

CREATE POLICY "Allow authenticated insert on hogar_snapshot" 
  ON public.hogar_snapshot FOR INSERT 
  TO authenticated 
  WITH CHECK (true);

CREATE POLICY "Allow authenticated update on hogar_snapshot" 
  ON public.hogar_snapshot FOR UPDATE 
  TO authenticated 
  USING (true);

-- 3. Create public.hogar_ninos table (many-to-many relationship)
CREATE TABLE IF NOT EXISTS public.hogar_ninos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_hogar bigint REFERENCES public.hogar(id) ON DELETE CASCADE NOT NULL,
  id_nino bigint REFERENCES public.niños(id_nino) ON DELETE CASCADE NOT NULL,
  activo boolean DEFAULT true NOT NULL,
  fecha_asociacion timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(id_nino, id_hogar)
);

-- Enable RLS for public.hogar_ninos
ALTER TABLE public.hogar_ninos ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow authenticated select on hogar_ninos" 
  ON public.hogar_ninos FOR SELECT 
  TO authenticated 
  USING (true);

CREATE POLICY "Allow authenticated insert on hogar_ninos" 
  ON public.hogar_ninos FOR INSERT 
  TO authenticated 
  WITH CHECK (true);

CREATE POLICY "Allow authenticated update on hogar_ninos" 
  ON public.hogar_ninos FOR UPDATE 
  TO authenticated 
  USING (true);
